### PR TITLE
Added product review functionality

### LINKED ISSUE #65: User must be able to leave a review on a product
"As a user, I want to be able to give my opinion on its quality."

_______________________________________________________________________________________________________________________________

###  >  **Story Point**

_______________________________________________________________________________________________________________________________

Story Points: 8

Explanation: We allocated the number 8 for this user story because this story is important for the user so that he can make 
a conscious decision on his purchases and the seller as well as another user can get feedback. For these reasons, this is 
an important story. However, it is of low risk; the website is still completely functional without it but it's a good feature to have to be fair with the users and give feedback to the sellers on their products.

______________________________________________________________________________________________________________________________

###  >  **Tasks Breakdown**

____________________________________________________________________________________________________________________________________

- [x] #66
- [x] #67
- [x] #68
- [x] #120
- [x] #121

_______________________________________________________________________________________________________________________________

## **>  Acceptance Test**

_________________________________________________________________________________________________________________________________

**Success:**

the user logs in to his account 
He then navigates to the browsing page. 
He searches an item he's interested in or simply finds it on the browsing page 
The user clicks on the item that interests him. 
He is directed to the product page of the item 
He goes down and clicks on leave a review.
He can add the number of stars he rates the product . 
He writes a review on why he likes or dislikes the product .
He sends the review 
The review is saved and everyone can see it .
The users and the sellers can read the review and make conscious changes and decisions concerning the product. 

**Failure:**
The user enters the product page 
He wants to leave a review.
The feature is not functional.
He cannot access it.
In another case, he could access it 
He writes his review 
Sadly, he is unable to save it 
The user was unable to leave a review or see other users' reviews.
The user is unable to make a conscious decision on his purchases and give feedback to the sellers or other users. 

___________________________________________________________________________________________________________________________________

### > **Risks, Priority & Countermeasures.**

______________________________________________________________________________________________________________________________

**High Priority**& **Low Risks**: The rating option is an important feature. The user has a right to give his opinion on the object he purchased. Moreover, the user's reviews will help future customers to make an informed choice and will provide important feedback to the seller. 

**Countermeasures:** 
1. The user will be redirected to an error page where they will be invited to follow a set of instructions in order to submit their review. The set of instructions will show the user how to send their review to a support team via email. The support team will then save the user's review and post it for them when the issue is fixed. The team will send the user an email once the review is successfully posted.
2. The error page will also provide a list of instructions for a second solution, which is to contact the admin directly via email and to let him know about the technical difficulties. The admin will then either fix the problem or delegate the task to an employee and will contact the user once the situation is dealt with.

### LINKED ISSUE #66: User should be able to submit a review by clicking the submit button.
**High Priority**: The addition of a review by the user is an important feature. The submit button has to be successfully implemented to have access to the review.

### LINKED ISSUE #67: User should have a text-box available titled "Leave a Review" where they can add a comment.

### LINKED ISSUE #68: User should also have a 5 star rating option in form of a drop-down menu.

### LINKED ISSUE #120: If a user has already reviewed a product, they may not submit another review of the product.

### LINKED ISSUE #121: Users must be logged in to an account to be able to review a product.

### PR DESCRIPTION
**Pull request by z-bruce**
----------------------------------------------------------------------------------------------------------------------------------------
**Description**
----------------------------------------------------------------------------------------------------------------------------------------
As an user, I want to be able to leave a review consisting of a rating between 1 to 5 

> Users can leave a review (consisting of a rating between 1 to 5 and a comment) of a product if they are logged into their account. Prevents users from submitting more than 1 review of a product. Calculates the average rating of the product based on the submitted reviews.

-----------------------------------------------------------------------------------------------------------------------------------------
###  Story Point
-------------------------------------------------------------------------------------------------------------------------------------------
**Story Points:** 8

**Explanation:** The users' ability to live a review is an important feature to reassure the users and build a relationship of security and trust with the user.However , these features does not affect the whole website.

------------------------------------------------------------------------------------------------------------------------------------------
###  Tasks Breakdown
-------------------------------------------------------------------------------------------------------------------------------------------
resolves #65 : Users must be able to leave a review on a product
resolves #66 : Users can submit a review by clicking the review button
resolves #67 : Users can add a comment to their review
resolves #68 : Users must include a rating between 1 to 5, accessible through a drop-down menu
resolves #120 : Users may only submit 1 review per product.
resolves #121 : Users must be logged in to an account to be able to review a product

-------------------------------------------------------------------------------------------------------------------------------------------
###  Acceptance Test
-------------------------------------------------------------------------------------------------------------------------------------------
**Success:**
The user logs into his account 
The user browses the products 
The user finds his product
He clicks on the product 
The user goes down and clicks on leaving a review. 
The user gives a rating from 1-5
The rating given is saved 
The user leaves a comment 
The comment is saved 
The user successfully left a review. 

**Failure:**
The user logs into his account 
The user browses the products 
The user finds his product 
He clicks on the product 
The user goes down and clicks on leaving a review 
Option 1 :
The user adds a rating on 1-5 
The rating is not saved 
Option 2 
The user adds a comments 
The comment is not saved 
In the end the user was not able to add a review successfully

-----------------------------------------------------------------------------------------------------------------------------------------
###  Risks, Priority & Countermeasures.
----------------------------------------------------------------------------------------------------------------------------------------
**Medium Priority& Low Risks:** The rating option is an important feature. The user has a right to give his opinion on the object he purchased. Moreover, the user's reviews will help future customers to make an informed choice and will provide important feedback to the seller.

### CODE REVIEW

**Comment by CarsonSSk** [comment]
Hey Zack, we carefully reviewed the commit and everything works fine.

**Comment by louisa-lina** [comment]
Organization of the informations

**Comment by louisa-lina** [comment]
addition of labels for the risk and priority

**Comment by CarsonSSk** [comment]
I reviewed the documentation and everything looks good!

**Pull request merged**
